export const contactos=[{"id":1,"nombre":"Wash","apellido":"Sawyer","email":"wsawyer0@icio.us","empresa":"Camimbo","domicilio":"Southridge","telefono":"829-631-2187"},
{"id":2,"nombre":"Even","apellido":"Tuxwell","email":"etuxwell1@ucsd.edu","empresa":"Blogtag","domicilio":"Hanover","telefono":"122-124-6564"},
{"id":3,"nombre":"Karlotta","apellido":"Slyme","email":"kslyme2@de.vu","empresa":"Livefish","domicilio":"Declaration","telefono":"531-801-6620"},
{"id":4,"nombre":"Hamel","apellido":"Mungan","email":"hmungan3@yandex.ru","empresa":"Voonte","domicilio":"Florence","telefono":"764-949-6447"},
{"id":5,"nombre":"Viviyan","apellido":"Poyle","email":"vpoyle4@oracle.com","empresa":"Rhynoodle","domicilio":"West","telefono":"291-235-3965"},
{"id":6,"nombre":"Eartha","apellido":"Helliar","email":"ehelliar5@businessweek.com","empresa":"Jatri","domicilio":"Dunning","telefono":"414-162-1415"},
{"id":7,"nombre":"Alyson","apellido":"Conen","email":"aconen6@studiopress.com","empresa":"Thoughtmix","domicilio":"Clarendon","telefono":"388-691-5130"},
{"id":8,"nombre":"Rodge","apellido":"McGinlay","email":"rmcginlay7@usa.gov","empresa":"Vipe","domicilio":"Drewry","telefono":"136-573-9034"},
{"id":9,"nombre":"Vikky","apellido":"Laybourn","email":"vlaybourn8@mac.com","empresa":"Quimba","domicilio":"Kingsford","telefono":"703-502-1027"},
{"id":10,"nombre":"Pegeen","apellido":"Klaus","email":"pklaus9@t-online.de","empresa":"Kanoodle","domicilio":"Jackson","telefono":"812-662-5573"}]